// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class CommentTravelerType
{
    public int CommentTravelerTypeId { get; set; }

    public int CommentId { get; set; }

    public int TravelerTypeId { get; set; }

    public virtual Comment Comment { get; set; }

    public virtual TravelerType TravelerType { get; set; }
}