// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class CommentWithInfo
{
    public int CommentId { get; set; }

    public string CommentTitle { get; set; }

    public string CommentText { get; set; }

    public DateTime CreatedAt { get; set; }

    public string FirstName { get; set; }

    public string TravelerType { get; set; }

    public string RoomTypeName { get; set; }
}