// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class Dialog
{
    public int DialogId { get; set; }

    public int MemberId { get; set; }

    public string Detail { get; set; }

    public int CalltoMemberId { get; set; }

    public DateTime CreateAt { get; set; }

    public virtual Member Member { get; set; }
}