// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class HotelType
{
    public int HotelTypeId { get; set; }

    public string HotelTypeName { get; set; }

    public virtual ICollection<Hotel> Hotels { get; set; } = new List<Hotel>();
}