// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class Hotel
{
    public int HotelId { get; set; }

    public string HotelName { get; set; }

    public string HotelAddress { get; set; }

    public string HotelPhone { get; set; }

    public string HotelDescription { get; set; }

    public int CityId { get; set; }

    public int HotelTypeId { get; set; }

    public int? LevelStar { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public virtual City City { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<HotelEquipmentReference> HotelEquipmentReferences { get; set; } = new List<HotelEquipmentReference>();

    public virtual ICollection<HotelImage> HotelImages { get; set; } = new List<HotelImage>();

    public virtual ICollection<HotelLike> HotelLikes { get; set; } = new List<HotelLike>();

    public virtual HotelType HotelType { get; set; }

    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();
}