// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class HotelImage
{
    public int HotelImageId { get; set; }

    public int HotelId { get; set; }

    public string HotelImage1 { get; set; }

    public virtual Hotel Hotel { get; set; }

    public virtual ICollection<ImageCategoryReference> ImageCategoryReferences { get; set; } = new List<ImageCategoryReference>();
}