// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class ImageCategoryReference
{
    public int ImageCategoryReferenceId { get; set; }

    public int ImageCategoryId { get; set; }

    public int HotelImageId { get; set; }

    public int? RoomImageId { get; set; }

    public virtual HotelImage HotelImage { get; set; }

    public virtual ImageCategory ImageCategory { get; set; }

    public virtual RoomImage RoomImage { get; set; }
}