// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class ImageCategory
{
    public int ImageCategoryId { get; set; }

    public string ImageCategoryName { get; set; }

    public virtual ICollection<ImageCategoryReference> ImageCategoryReferences { get; set; } = new List<ImageCategoryReference>();
}