// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class RatingScore
{
    public int RatingId { get; set; }

    public int? CommentId { get; set; }

    public int? RoomId { get; set; }

    public decimal? ComfortScore { get; set; }

    public decimal? CleanlinessScore { get; set; }

    public decimal? StaffScore { get; set; }

    public decimal? FacilitiesScore { get; set; }

    public decimal? ValueScore { get; set; }

    public decimal? LocationScore { get; set; }

    public decimal? FreeWifiScore { get; set; }

    public string TravelerType { get; set; }

    public virtual Comment Comment { get; set; }

    public virtual Room Room { get; set; }
}