// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class ReportTitle
{
    public int ReportTitleId { get; set; }

    public string ReportTitle1 { get; set; }

    public virtual ICollection<ReportReview> ReportReviews { get; set; } = new List<ReportReview>();

    public virtual ICollection<ReportSubtitle> ReportSubtitles { get; set; } = new List<ReportSubtitle>();
}