// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class RoomType
{
    public int RoomTypeId { get; set; }

    public string RoomTypeName { get; set; }

    public string Icon { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();
}