// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class RoomEquipmentReference
{
    public int RoomEquipmentReferenceId { get; set; }

    public int RoomId { get; set; }

    public int RoomEquipmentId { get; set; }

    public virtual Room Room { get; set; }

    public virtual RoomEquipment RoomEquipment { get; set; }
}