// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class Room
{
    public int RoomId { get; set; }

    public int HotelId { get; set; }

    public string RoomName { get; set; }

    public decimal RoomPrice { get; set; }

    public string Description { get; set; }

    public int RoomTypeId { get; set; }

    public bool? RoomStatus { get; set; }

    public decimal? RoomSize { get; set; }

    public int MaximumOccupancy { get; set; }

    public int MemberId { get; set; }

    public virtual Hotel Hotel { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<RatingScore> RatingScores { get; set; } = new List<RatingScore>();

    public virtual ICollection<RoomEquipmentReference> RoomEquipmentReferences { get; set; } = new List<RoomEquipmentReference>();

    public virtual ICollection<RoomImage> RoomImages { get; set; } = new List<RoomImage>();

    public virtual RoomType RoomType { get; set; }
}