// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PrjFunNowWeb.Models;

public partial class TravelerType
{
    public int TravelerTypeId { get; set; }

    public string TravelerType1 { get; set; }

    public virtual ICollection<CommentTravelerType> CommentTravelerTypes { get; set; } = new List<CommentTravelerType>();
}